### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-ui#1]
We want this to be a library that can be easily imported in our apps and we want to use tags for npm releases, follow the same release structure than LifToken and wt-contracts repo.

**Comment by JirkaChadima** [comment]
@beogip Thanks for the tip. It's already on our wishlist, but since we're still on `0.x` releasing branch, we've decided to hold semantic-release for a little bit of time. But we're trying to get there!

**Comment by MatiasOS** [comment]
closed by #65
