### ISSUE TITLE
Static site is not working properly

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/wt-ui#12]
Building static storybook site, is taking the styles from `src` instead of `dist`. This is wrong because we want Storybook to be using the same as the client apps.

We need a way to differentiate when we run dev and prod modes.

**Comment by JirkaChadima** [comment]
This seems to be fixed by #16 (https://github.com/windingtree/wt-ui/commit/90b839d1a3ba4ace6b4fa400f6fc58c52a114c6e). Can this be closed @MatiasOS ?

**Comment by MatiasOS** [comment]
yes!
