### ISSUE TITLE
Use test app with all styleguide resources for testing.

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-ui#2]
We want only install and test instructions, the tests can be done running a test app, this app can be located in the test folder, will be similar to what we have right now runing with `npm run dev`, but in this case it will be  and app hosted on localhost once `npm test` run.

Depends on https://github.com/windingtree/wt-ui/issues/1

**Comment by skkr** [comment]
We are using Storybook for testing components. ```npm run storypook-dev``` opens it in dev mode, with hot reload.
