### ISSUE TITLE
Make sure Bootstrap's components that require javascript, work well.

### ISSUE THREAD

**Issue by skkr** [windingtree/wt-ui#22]
@PabloAlice, as we discussed, currently some components only work after reloading Storybook.

**Comment by skkr** [comment]
@pabloalice please review the navbar component, it has a weird behavior after the merge. After expand it and closing it once, it gets expanded again without users intervention. Also keep the original markup, since is intended to serve a a complete example on how to use the component, the items on the menu must be there.

Just in case, we shouldn't change the markup of the stories except to add required attributes, and if we do, the related mark-down file must be also updated, but since the stories markup was defined specifically to be in line with what the documentation says, is preferred to avoid changes.

cc @MatiasOS

**Comment by PabloAlice** [comment]
I'm sorry about the markup changes, it was a mistake I got checking something !.
I will fix it as soon as possible!

**Comment by skkr** [comment]
@PabloAlice when you can, please review the javascript code used by the navbar component, on mobile, it expands but cannot be collapsed.

https://storybook-ef67b.firebaseapp.com/?selectedKind=Navigation&selectedStory=Navbar&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook-addon-viewport%2Faddon-panel

**Comment by skkr** [comment]
@PabloAlice can you give it a look?

**Comment by PabloAlice** [comment]
yes, I will be working on it this week.

**Comment by skkr** [comment]
Great, thanks!

**Comment by skkr** [comment]
I'll close this untill we can discuss a better approach.
