### ISSUE TITLE
Use media resources from media repository

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-ui#3]
Use all the media resources from https://github.com/windingtree/media repository, I guess a git submodule will be enough.

Depends on https://github.com/windingtree/media/issues/3.

**Comment by JirkaChadima** [comment]
Please, don't use git submodules. Like ever. That's a hell no one wants. We should either release media repo to npm or install it as an npm dependency directly from github.

**Comment by JirkaChadima** [comment]
In the end, we don't actually have to create an npm release of `media` repo, something like `npm install windingtree/media` should work as well. And even if it's just pictures we want to have them always in a current state anyways, so referencing master should not be a problem.

**Comment by skkr** [comment]
Perhaps we could have a secondary branch without the editable assets (.ai files), since most probably they won't be necessary except for specific situations. Do you think it make sense?

**Comment by JirkaChadima** [comment]
It probably makes sense... Maybe we could drop other files from that branch as well (such as `styleguide.pdf`). Downloading 22 MB of logos probably isn't something you want to do on every `npm install`. What if we would create a branch with logos (and other stuff) ready for web only? It would contain multiple logo sizes, favicons etc..

**Comment by skkr** [comment]
Yes, it seems as a good idea, if we all agree lets do it that way.

**Comment by skkr** [comment]
@JirkaChadima is done, in case you wanna check: https://github.com/windingtree/media/tree/web-assets

@menschikov for our to do list, we should probably generate and keep all the logo variants on this branch, so they are ready to use.

**Comment by JirkaChadima** [comment]
@skkr Looks good! What about the `old-assets` directory? Do we need to keep that around since we're rebranding everything?

**Comment by skkr** [comment]
@JirkaChadima I was unsure about it, but I would say we don't. I'll remove it!

**Comment by skkr** [comment]
@AugustoL Done! 

There are a few images that we should include in the `web-assets` branch of the `media` repo, but that's not really related to this issue so I  guess we can close it. 

Regarding to the missing images, @menschikov is going to take care of it after site deploy.
