### ISSUE TITLE
The javascript file in the /dist folder should include botstrap's and our custom javascript

### ISSUE THREAD

**Issue by skkr** [windingtree/wt-ui#70]
We are extending Bootstrap, so it shouldn't be necessary to use wi-ui alongside Bootstrap. When using it on an app, it should be enough to include the .css and .js files from wt-ui.

**Comment by skkr** [comment]
@MatiasOS, @PabloAlice we should add bootstrap.js and popper.js to the dist folder instead the JS file we have now (which seems to be wrong, btw). If we have custom JS it should be added to that folder too.

Optionally we could link to the files directly in index.html

@AugustoL, @JirkaChadima please advice.

**Comment by JirkaChadima** [comment]
JS and CSS are two totally different animals.

You don't actually need bootstrap's js if you're not using any of their dynamic components. That's why I'd go opt-in for that. Either way, this has to be carefully documented, so the libraries are not loaded twice.

**Comment by skkr** [comment]
Yeah, I meant, if someone is already using bootstrap it would be probably for the CSS, which is included in our framework already, so it could be safely replaced with our framework instead of keeping them both.

For the JS, I agree, it should be optional. We'll need to have some custom functionality thought, to for example control the behavior of the header (triggered by the page scrolling), the horizontal scrolling logos, something for the sticky footer, etc.

So at the end, on the dist folder we should have.

- Our CSS file
- Our JS file
- Bootstrap's JS file

**Comment by JirkaChadima** [comment]
I would actually do two different JS builds: One only with our functionality and the other with vendor dependencies (popper, bootstrap) included.

Everyone can then choose if they want to use a bundled version, use CDN or their own build system.

As for the CSS part: If our CSS code doesn't make any sense without bootstrap's CSS, I wouldn't separate them.

But probably most importantly, we should keep the `src/` as part of the distributed package as well. If anyobody needs something very special, they can build it in any way they want directly from source.

**Comment by skkr** [comment]
Thanks @JirkaChadima, sounds good to me. @MatiasOS , @PabloAlice could you guys take care of this?

**Comment by skkr** [comment]
Just created a new issue based on what @JirkaChadima suggested. Closing this one.
